### ISSUE TITLE
[모집중] 2022년도 상반기 회고모임 발표자 모집합니다!

### ISSUE THREAD

**Issue by uhhyunjoo** [sejonginterface/InterfaceWritingCircle#1]
- 발표하실 분들은 아래에 `발표 신청합니다!` 라고 `comment` 남겨주시면 감사하겠습니다.
- 어떤 내용이 담긴 발표를 할 예정인지 대략적인 키워드를 함께 남겨주시면 좋을 것 같습니다! 😉
- 이후 발표 자료는 해당 레포에 `PR` 로 보내주시면 `merge` 하도록 하겠습니다. (이에 대한 안내는 회고모임 이후 진행할 예정입니다!)

**Comment by uhhyunjoo** [comment]
발표 신청합니다!

키워드 : 대학원, 연구 vs 개발, 오픈소스 컨트리뷰션, 인터페이스, 해커톤

**Comment by riyenas0925** [comment]
발표 신청해요~

키워드 : 개발자의 오픈소스 도전기, 조금이라도 빨리 알았더라면 좋았을 것들, 2022년 상반기 회고 중 하나

**Comment by dev210202** [comment]
발표신청
키워드: 나는 '이것'을 본 이후로 미쳐버렸고, 후회했고, [      ]했다.
